### ISSUE TITLE
Anonymous user cart item removal

### ISSUE THREAD

**Issue by ScottLockett** [marktheskies/theidleman#35]
If a user is not signed in and adds an item to the cart they cannot remove it. When attempted there was an error - refer attached image
![image](https://user-images.githubusercontent.com/76945248/107357220-c000f580-6b0c-11eb-8f81-d889e6c640a4.png)

**Comment by marktheskies** [comment]
I'm aiming to resolve this in a new PR, will keep you posted @ScottLockett
